// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VShop.DiscountApi.Context;

#nullable disable

namespace VShop.DiscountApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VShop.DiscountApi.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "VSHOP_PROMO_10",
                            Discount = 10m
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "VSHOP_PROMO_20",
                            Discount = 20m
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "VSHOP_PROMO_30",
                            Discount = 30m
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "VSHOP_PROMO_40",
                            Discount = 40m
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "VSHOP_PROMO_50",
                            Discount = 50m
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "VSHOP_PROMO_60",
                            Discount = 60m
                        },
                        new
                        {
                            CouponId = 7,
                            CouponCode = "VSHOP_PROMO_70",
                            Discount = 70m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
