# name: Deploy Application with EF Migrations

# on:
  # push:
# #    branches: [ main ]

# jobs:
  # deploy:
    # runs-on: ubuntu-latest
    
    # steps:
      # - uses: actions/checkout@v4

      # - name: Setup .NET
        # uses: actions/setup-dotnet@v4
        # with:
          # dotnet-version: '9.0.x'

      # - name: Restore dependencies
        # run: dotnet restore GettingStartedWithEfCore.sln

      # - name: Build
        # run: dotnet build GettingStartedWithEfCore.sln --configuration Release --no-restore -o ${{env.DOTNET_ROOT}}/myapp

      # - name: Create EF Migration Bundle
        # run: |
          # dotnet tool install --global dotnet-ef
          # dotnet ef migrations bundle --project Movies.Api/Movies.Api.csproj --output efbundle

      # - name: Run EF Migrations
        # run: ./efbundle --connection "${{ secrets.DB_CONNECTION_STRING }}"

      # - name: Deploy to Azure Web App
        # uses: azure/webapps-deploy@v3
        # with:
          # app-name: migrations-movies-api
          # slot-name: 'Production'
          # publish-profile: ${{ secrets.AZURE_MOVIES_API_PUBLISH_PROFILE }}
          # package: ${{env.DOTNET_ROOT}}/myapp 