@HostAddress = https://localhost:7193

### Auth: Get
GET {{HostAddress}}/api/v1/auth
Accept: application/json
###

### Auth: Create
GET {{HostAddress}}/api/v1/auth
Content-Type: application/json
{
    "name": "Personal 004",
    "email": "perssonal.001@gmail.com",
    "password": "12345678"
}
###

### Data: Get
GET {{HostAddress}}/api/v1/data
Accept: application/json
###