// <auto-generated />
using System;
using CMS_DotNet_Teste_Resquest_Http_FoxBit_Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS_DotNet_Teste_Resquest_Http_FoxBit_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231202024525_AddTablesInitOnDataTablesDb")]
    partial class AddTablesInitOnDataTablesDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CMS_DotNet_Teste_Resquest_Http_FoxBit_Api.Models.TradeModel", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("client_order_id")
                        .HasColumnType("numeric(15,0)")
                        .HasColumnName("client_order_id");

                    b.Property<DateTime>("created_at")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("funds_received")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("funds_received");

                    b.Property<decimal>("instant_amount")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("instant_amount");

                    b.Property<decimal>("instant_amount_executed")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("instant_amount_executed");

                    b.Property<string>("market_symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("market_symbol");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("price");

                    b.Property<decimal>("price_avg")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("price_avg");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("quantity_executed")
                        .HasColumnType("decimal(21,8)")
                        .HasColumnName("quantity_executed");

                    b.Property<string>("remark")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("remark");

                    b.Property<string>("side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("side");

                    b.Property<string>("sn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sn");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<decimal>("trades_count")
                        .HasColumnType("numeric(9,0)")
                        .HasColumnName("trades_count");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.HasKey("id")
                        .HasName("PkTnBFoxbit_Trades");

                    b.ToTable("TbTnBFoxbit_Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
