version: "3.5"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    restart: always
    environment:
      - DB_HOSTNAME=db
    # ports:
    #   - "3001:8080"
    depends_on:
      - db

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    # ports:
    #   - "3002:8080"
 
  nginx:
    #container_name: wrk-web-nginx
    image: nginx:latest  # nginx:1.21.6-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999" 
    depends_on:
      - api01
      - api02

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped # always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
