@HostAddress = https://localhost:7256/api/v1/auth

### Add user
POST {{HostAddress}}/register
Content-Type: application/json
{
    "userName": "admin",
    "firstName": "Administrador", 
    "password": "Abc123!", 
    "email": "administrador@gmail.com",
    "telefone": "(12)912345678"
}
###

### Add scope to user
POST {{HostAddress}}/grant
Content-Type: application/json
{
    "userName": "admin",
    "Scopes": "api,front,frontend"
}
###

### Add role to user
POST {{HostAddress}}/role
Content-Type: application/json
{
    "userName": "admin",
    "role": "full"
}
###

### Get all users
GET {{HostAddress}}/users
Accept: application/json
###

### Get Token
POST {{HostAddress}}/token
Content-Type: application/json
{
    "client_id": "admin",
    "client_secret": "Abc123!", 
    "grant_type": "client_credentials",
    "scope": "api"
}
###Content-Type: application/x-www-form-urlencoded
###> {% 
###  const response = await response.json();
###  client.global.set("access_token", response.access_token);
###%}
###

### Get authorize
GET {{HostAddress}}/authorize-only
Authorization: Bearer {{access_token}}
###

### Get full
GET {{HostAddress}}/full-only
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmI4YTlmOTU3ZDBlNDY0ZGI2YWQwOTM4OWU1MzA3NTIiLCJkaXNwbGF5X25hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZSI6ImZ1bGwiLCJhdWQiOlsiZnJvbnQiLCJhcGkiLCJhdWRpZW5jZSJdLCJleHAiOjE3NDkzOTE4MzUsImlzcyI6Im9hdXRoIn0.nI4AWPar94kdQZI0bvOfUFa2CP6XPXbhyS5L1xXXZTUjZqUpz5aBKwKYi1GRy_PaEK_tekL4msDikt28vkBExQ
###

### Get admin
GET {{HostAddress}}/admin-only
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmI4YTlmOTU3ZDBlNDY0ZGI2YWQwOTM4OWU1MzA3NTIiLCJkaXNwbGF5X25hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZSI6ImZ1bGwiLCJhdWQiOlsiZnJvbnQiLCJhcGkiLCJhdWRpZW5jZSJdLCJleHAiOjE3NDkzOTE4MzUsImlzcyI6Im9hdXRoIn0.nI4AWPar94kdQZI0bvOfUFa2CP6XPXbhyS5L1xXXZTUjZqUpz5aBKwKYi1GRy_PaEK_tekL4msDikt28vkBExQ
###
