//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbItemVenda
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }
        public int Quantidade { get; set; }
        public Nullable<int> Venda_Id { get; set; }
    
        public virtual TbVenda TbVenda { get; set; }
    }
}
