//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbVaga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbVaga()
        {
            this.TbRequisito = new HashSet<TbRequisito>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public decimal Salario { get; set; }
        public bool Ativa { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string LocalTrabalho { get; set; }
        public int EmpresaId { get; set; }
    
        public virtual TBEmpresa TBEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbRequisito> TbRequisito { get; set; }
    }
}
